// Run with node model/drivetrain/verify.cjs. Bundled Playwright or PLAYWRIGHT_MODULE is required.
const fs=require('fs'),path=require('path'),assert=require('assert');
const d=require('./geometry.js');
for(const rack of [-1.5,0,1.5]){const st=d.state({rack});assert(st.solutions.every(s=>s.valid));for(const s of st.solutions){assert(Math.abs(d.steeringPoint(s.s,s.theta,0).distanceTo(d.rackPoint(s.s,rack,0))-d.rodLength(s.s))<1e-7)}}
const left=d.state({rack:1.5}).solutions,right=d.state({rack:-1.5}).solutions;assert(Math.abs(left[0].theta+right[1].theta)<1e-8);
const k8=d.state({kneel:8});assert(k8.bagH<d.cfg.bagMin);assert(d.build({kneel:8}).metrics.clashes.length>0);const k3=d.state({kneel:3});assert(k3.solutions.every(s=>s.valid&&Math.abs(s.theta)<2.5*Math.PI/180));assert(d.build({rack:2.5}).metrics.clashes.length===0);
let model=d.build({});assert(model.metrics.parts>1000);assert.deepEqual(model.metrics.clashes,[]);const ex=d.obj(model.group);assert(ex.obj.includes('LF280K_string_2_cell_16'));assert(ex.obj.includes('M24_thread'));assert(!/\b(NaN|Infinity)\b/.test(ex.obj));
fs.writeFileSync(path.join(__dirname,'drivetrain.obj'),ex.obj);fs.writeFileSync(path.join(__dirname,'drivetrain.mtl'),ex.mtl);
fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({date:'2026-09-13',default:model.metrics,steerRack15:d.state({rack:1.5}),steerRack25:{...d.state({rack:2.5}),clashes:d.build({rack:2.5}).metrics.clashes},kneel3:k3,kneel8:{...k8,clashes:d.build({kneel:8}).metrics.clashes},checks:['fixed tie-rod lengths','left/right symmetry','toe under 2.5 deg at 3 in kneel','no sampled clash at full rack travel','bag below 2.8 in and receiver clash at 8 in kneel','named finite meter-scale OBJ'],meshCount:model.metrics.parts},null,2));
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/zeke/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch(process.env.PLAYWRIGHT_MODULE?{headless:true}:{headless:true,channel:'chrome'});const page=await b.newPage({viewport:{width:1600,height:1040},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file://'+path.resolve(__dirname,'../drivetrain-3d.html'));await page.waitForFunction(()=>window.drivetrainModel&&window.drivetrainRenderer);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(__dirname,'drivetrain-overview.png')});
await page.locator('[data-view=corner]').click();await page.locator('#explode').fill('75');await page.locator('#explode').dispatchEvent('input');await page.waitForFunction(()=>window.drivetrainModel.metrics.explode===75&&window.drivetrainModel.group.children.some(o=>o.name==='FRONT_LEFT'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(__dirname,'drivetrain-front-corner.png')});
await page.locator('[data-view=top]').click();await page.locator('#rack').fill('1.5');await page.locator('#rack').dispatchEvent('input');await page.waitForFunction(()=>Math.abs(window.drivetrainModel.metrics.travel-1.5)<1e-8);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(__dirname,'drivetrain-steering-plan.png')});
await page.locator('#kneel').fill('8');await page.locator('#kneel').dispatchEvent('input');await page.waitForFunction(()=>window.drivetrainModel.metrics.k===8);assert((await page.locator('#motionWarnings').innerText()).includes('compressed-height'));
await page.locator('#kneel').fill('0');await page.locator('#kneel').dispatchEvent('input');await page.locator('#rack').fill('0');await page.locator('#rack').dispatchEvent('input');await page.locator('[data-view=iso]').click();
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(__dirname,'drivetrain-mobile.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',errors,meshCount:model.metrics.parts,objBytes:ex.obj.length,images:['overview','front-corner','steering-plan','mobile']}));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
