(function(){'use strict';const $=id=>document.getElementById(id);if(!window.THREE||!window.DriveModel){$('error').textContent='The local 3D library could not load. Keep the drivetrain folder beside this file.';return}
const T=THREE,stage=$('viewport'),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0xedf0eb);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;stage.prepend(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,2000);scene.add(new T.HemisphereLight(0xffffff,0x9caba6,.8));const sun=new T.DirectionalLight(0xfff7e8,.8);sun.position.set(40,170,100);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-110,right:110,top:100,bottom:-100,near:1,far:400});sun.shadow.bias=-.0008;scene.add(sun);const fill=new T.DirectionalLight(0xcfe6ec,.25);fill.position.set(-70,60,-90);scene.add(fill);
const floor=new T.Mesh(new T.PlaneGeometry(2000,2000),new T.MeshStandardMaterial({color:new T.Color(0xe5e9e1).convertSRGBToLinear(),roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.5;floor.receiveShadow=true;scene.add(floor);const grid=new T.GridHelper(240,20,0xc1cdc5,0xd5ddd4);grid.position.y=-.4;scene.add(grid);
const controls={rack:0,kneel:0,explode:0,mass:2000,crr:.06,grade:0,accel:0,eta:.7,usable:24.5,other:6,wind:0,cda:8,chg:2.2,mode:'assembly',hideTires:false,hideBattery:false};let model,az=.85,el=.55,dist=225,target=new T.Vector3(6,12,0),drag=null,currentView='iso',selected='knuckle',pending=false;
const labelInfo={frame:['01','Ladder frame'],receivers:['02','Receiver sleeves'],battery:['03','32-cell battery sled'],controller:['04','4 × controllers'],air:['05','Air supply'],spring:['06','D2500 spring'],steering:['07','Rack + tie rods'],knuckle:['08','Custom knuckle'],motor:['09','QS205 car motor*'],wheel:['10','12 in wheel + tire'],controls:['11','Driver controls'],brakes:['12','Service brake*']};
function select(key){selected=key;const p=DriveModel.parts[key]||DriveModel.parts.knuckle;$('partTitle').textContent=p.title;$('partKind').textContent=p.kind;$('partText').textContent=p.text;$('partSource').href=p.source||'drivetrain-review.md';}
function place(){const fitDist=dist*Math.max(1,1.25/camera.aspect);camera.position.set(target.x+fitDist*Math.cos(el)*Math.sin(az),target.y+fitDist*Math.sin(el),target.z+fitDist*Math.cos(el)*Math.cos(az));camera.lookAt(target);}
function labels(){const layer=$('annotation-layer');layer.replaceChildren();if(!$('labels').checked)return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.style.position='absolute';svg.style.inset='0';svg.id='leaders';layer.append(svg);const names=controls.mode==='corner'?['knuckle','motor','wheel','spring','brakes']:stage.clientWidth<700?['battery','motor','knuckle','controls']:['frame','battery','spring','steering','motor','controls'];
 for(const key of names){if(!model.anchors[key]||(controls.hideBattery&&key==='battery'))continue;const b=document.createElement('button');b.className='callout';b.dataset.part=key;b.innerHTML=`<b>${labelInfo[key][0]}</b>${labelInfo[key][1]}`;b.onclick=()=>select(key);layer.append(b);const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.id='leader-'+key;l.setAttribute('stroke','#7e9890');l.setAttribute('stroke-width','1');svg.append(l);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.id='dot-'+key;dot.setAttribute('r','2.5');dot.setAttribute('fill','#278b89');svg.append(dot)} }
function positionLabels(){const occupied=[];const rect=stage.getBoundingClientRect();const w=rect.width,h=rect.height;for(const b of $('annotation-layer').querySelectorAll('.callout')){const key=b.dataset.part,p=model.anchors[key].clone().project(camera);if(p.z>1){b.style.display='none';continue}b.style.display='flex';const px=(p.x*.5+.5)*w,py=(-p.y*.5+.5)*h;let x=px,y=py-27;const bw=b.offsetWidth,bh=b.offsetHeight;x=Math.max(bw/2+6,Math.min(w-bw/2-6,x));y=Math.max(86,Math.min(h-92,y));for(let attempts=0;attempts<16;attempts++){if(!occupied.some(r=>Math.abs(x-r.x)<(bw+r.w)/2+6&&Math.abs(y-r.y)<(bh+r.h)/2+6))break;y-=bh+6;if(y<80){y=h-110;x=Math.min(w-bw/2-6,x+30)}}occupied.push({x,y,w:bw,h:bh});b.style.left=x+'px';b.style.top=y+'px';const l=$('leader-'+key),dot=$('dot-'+key);if(l){l.setAttribute('x1',px);l.setAttribute('y1',py);l.setAttribute('x2',x);l.setAttribute('y2',y);dot.setAttribute('cx',px);dot.setAttribute('cy',py)}} }
function updateReadouts(){const q=model.metrics,c=DriveModel.cfg,s=q.solutions;const values=[['Front right / left',s.map(a=>(a.theta*180/Math.PI).toFixed(1)+'°').join(' / ')],['Tie rods / closure',q.rodLengths[0].toFixed(2)+' in · '+(s.every(a=>a.valid)?'solved':'NO SOLUTION')],['Spring height, approximate',q.bagH.toFixed(2)+' in'],['Battery ground clearance',q.clearance.toFixed(1)+' in'],['Toe at this kneel, centred rack',controls.rack===0?(Math.abs(s[1].theta)*180/Math.PI).toFixed(2)+'°':'—'],['Tire OD / width',c.tireD.toFixed(2)+' / '+c.tireW.toFixed(2)+' in'],['Straight tire outer width',(c.track+c.tireW).toFixed(2)+' in'],['Scrub radius, hub height / ground',q.scrubHub.toFixed(1)+' / '+q.scrubGround.toFixed(1)+' in'],['Kingpin inclination / pin',(c.kpi*180/Math.PI).toFixed(0)+'° / '+c.kingpinD+' in']];
 $('metrics').innerHTML=values.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('');let warnings=[];
 if(!s.every(a=>a.valid))warnings.push(['bad','Steering cannot close at this position. The drawn angle is only the nearest attempted solution.']);
 if(q.bagH<c.bagMin)warnings.push(['bad','Air spring is below its 2.8 in compressed-height limit.']);else if(q.bagH<5.5)warnings.push(['','Air spring below its normal design-height range. Kneel only remains a proposal.']);
 if(q.clearance<3)warnings.push(['bad','Battery is below the proposed 3 in minimum ground clearance.']);
 if(q.clashes.length&&!controls.explode)warnings.push(['bad','Sampled tire intersection: '+q.clashes.map(x=>({frame:'side rail',receivers:'receiver sleeve',arms:'arm leg',spring:'air spring'})[x]||x).join(', ')+'.']);
 if(controls.explode)warnings.push(['','Exploded display. Clearances do not apply to separated parts.']);
 if(!warnings.length)warnings.push(['','Interfaces remain provisional. Exact motor, wheel, brake and bearing fit is not approved.']);
 $('motionWarnings').innerHTML=warnings.map(([cl,t])=>`<div class="warning ${cl}">${t}</div>`).join('');
 $('loadText').textContent=`${q.rpm.toFixed(0)} rpm at 5 mph · ${q.torque.toFixed(0)} N·m per wheel (rolling ${q.tRoll.toFixed(0)} + grade ${q.tGrade.toFixed(0)} + acceleration ${q.tAccel.toFixed(0)}) · ${(q.torque*4*q.rpm*2*Math.PI/60/1000).toFixed(1)} kW total at the wheels.`;
 $('rackOut').textContent=controls.rack.toFixed(2)+' in';$('kneelOut').textContent=controls.kneel.toFixed(1)+' in';$('explodeOut').textContent=controls.explode+'%';$('massOut').textContent=controls.mass.toLocaleString()+' kg';$('crrOut').textContent=controls.crr.toFixed(3);$('gradeOut').textContent=controls.grade.toFixed(1)+' %';$('accelOut').textContent=controls.accel.toFixed(2)+' m/s²';$('etaOut').textContent=(controls.eta*100).toFixed(0)+' %';$('usableOut').textContent=controls.usable.toFixed(1)+' kWh';$('otherOut').textContent=controls.other.toFixed(1)+' kWh';$('windOut').textContent=controls.wind.toFixed(0)+' mph';$('chgOut').textContent=controls.chg.toFixed(1)+' kW';
 const r=q.range;$('rangeText').textContent=`${r.whPerMile.toFixed(0)} Wh per mile from the pack (${r.kwMoving.toFixed(1)} kW while moving${r.fAero>50?', '+r.fAero.toFixed(0)+' N of wind drag':''}) · ${r.driveKwh.toFixed(1)} kWh left for driving → ${r.miles.toFixed(0)} miles, ${r.hours.toFixed(1)} h of motion at 5 mph. At Crr 0.03 / 0.06 / 0.10: ${r.byCrr.map(b=>b.miles.toFixed(0)).join(' / ')} miles. Recharging the ${controls.usable.toFixed(1)} kWh at ${controls.chg.toFixed(1)} kW into the pack: ${(controls.usable/controls.chg).toFixed(1)} h.`;
}
function rebuild(){if(model){scene.remove(model.group);const mats=new Set();model.group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)mats.add(o.material)});mats.forEach(m=>m.dispose())}model=DriveModel.build(controls);scene.add(model.group);labels();updateReadouts();window.drivetrainModel=model;}
function schedule(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;rebuild()})}
function view(name){currentView=name;controls.mode=name==='corner'?'corner':'assembly';if(name!=='corner'){controls.explode=0;$('explode').value=0}$('section-explode').style.display=name==='corner'?'block':'none';for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===name));
 const presets={iso:[.85,.55,225,[6,12,0]],top:[0,Math.PI/2-.0001,224,[5,10,0]],side:[0,.025,225,[7,19,0]],front:[Math.PI/2,.06,164,[15,17,0]],corner:[-1.35,.42,106,[37,15,25]]};const v=presets[name];[az,el,dist]=v;target.set(...v[3]);$('viewTitle').textContent=name==='corner'?'The front corner: where precision work concentrates.':'A purchased motor still needs a custom wheel end.';rebuild();place();}
for(const key of ['rack','kneel','explode','mass','crr','grade','accel','eta','usable','other','wind','chg'])$(key).addEventListener('input',e=>{controls[key]=Number(e.target.value);schedule()});for(const key of ['hideTires','hideBattery'])$(key).addEventListener('change',e=>{controls[key]=e.target.checked;schedule()});$('labels').onchange=labels;for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.shiftKey||e.button===2};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(drag.pan){const right=new T.Vector3().crossVectors(camera.getWorldDirection(new T.Vector3()),camera.up).normalize();target.addScaledVector(right,-dx*dist*.001);target.y+=dy*dist*.001}else{az-=dx*.006;el=Math.max(.015,Math.min(Math.PI/2-.001,el+dy*.006))}place()});canvas.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<4){const rect=canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hits=ray.intersectObject(model.group,true).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent}return h.object.userData.part});if(hits.length)select(hits[0].object.userData.part)}drag=null});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(45,Math.min(500,dist*Math.exp(e.deltaY*.001)));place()},{passive:false});
function save(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Saved '+name}
$('exportObj').onclick=()=>save(DriveModel.obj(model.group).obj,'drivetrain.obj','text/plain');$('exportMtl').onclick=()=>save(DriveModel.obj(model.group).mtl,'drivetrain.mtl','text/plain');$('exportPng').onclick=()=>{renderer.render(scene,camera);canvas.toBlob(b=>save(b,'drivetrain-view.png','image/png'))};
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight,false);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();place();if(model)labels()}new ResizeObserver(resize).observe(stage);select('knuckle');rebuild();resize();place();window.drivetrainView=view;window.drivetrainControls=controls;window.drivetrainRebuild=rebuild;window.drivetrainRenderer=renderer;
(function loop(){renderer.render(scene,camera);positionLabels();requestAnimationFrame(loop)})();
})();
